---
- hosts: junos
  gather_facts: no

  vars_prompt:
  - name: USERNAME
    prompt: Username
    private: no
  - name: PASSWORD
    prompt: Password
    private: yes

  vars:
    ansible_user: "{{ USERNAME }}"
    ansible_password: "{{ PASSWORD }}"

  tasks:
  - name: Get Version
    junos_command:
      commands:
        - show version
    register: printout
  - name: Save Output
    lineinfile:
      path: versions.log
      create: yes
      line: "{{printout.stdout_lines}}"
    register: version
